# Generated by Django 4.2.23 on 2025-08-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tumbnail_post_updated_at_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tumbnail',
            new_name='thumbnail',
        ),
    ]
